apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  rancher.server: |
    rancher.${LAB_DOMAIN}:53 {
      hosts {
        ${LAB_IP} rancher.${LAB_DOMAIN}
      }
    }
  s3.server: |
    s3.${LAB_DOMAIN}:53 {
      hosts {
        ${LAB_IP} s3.${LAB_DOMAIN}
      }
    }
