apiVersion: v1
kind: Pod
metadata:
  name: writer
  namespace: pvc-demo
spec:
  containers:
    - name: writer
      image: curlimages/curl:latest
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "date >> /data/log.txt; cat /data/log.txt; sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo-data
